type: bulk
args:

#Insert Author table data
- type: insert
  args:
    table: author
    objects:
      - name: Author 1
        info:
          age: 23
        location:
          type: Point
          coordinates:
          - -118.4079
          - 33.9434
      - name: Author 2

#Insert Person table data
- type: insert
  args:
    table: person
    objects:
    - details:
        name:
          first: foo
          last: bar
        address: foobar

#Insert numerics table data
- type: insert
  args:
    table: numerics
    objects:
    - num_smallint: 12345
      num_integer: 12345
      num_bigint: 12345
      num_real: 500002
      num_double: 500000000000002
      num_money: 12345.67
      num_numeric: 12345.67
    - num_smallint: 12345
      num_integer: 12345
      num_bigint: 12345
      num_real: 500002
      num_double: 500000000000002
      num_money: 12345.67
      num_numeric: 12345.67
