[package]
name = "tracing-util"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
derive_more = "0.99.17"
http = "0.2.9"
# version > 0.20 of opentelemetry doesn't work well with our tracing-utils
opentelemetry = "0.20.0"
opentelemetry-contrib = "0.12.0"
opentelemetry-http = "0.9.0"
opentelemetry-otlp = "0.13.0"
opentelemetry_sdk = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-semantic-conventions = "0.12.0"

[dev-dependencies]
axum = "0.6"

[package.metadata.cargo-machete]
ignored = [
  "axum", # used in doc examples
]
