type: bulk
args:
- type: run_sql
  args:
    sql: |
      -- insert data
      INSERT INTO author (name)
        VALUES ('Author 1'), ('Author 2')
      ;
      INSERT INTO article (title, content, author_id)
        VALUES
        ( 'Article 1'
        , 'Content for Article 1'
        , 1
        ),
        ( 'Article 2'
        , 'Content for Article 2'
        , 1
        ),
        ( 'Article 3'
        , 'Content for Article 3'
        , 2
        )
      ;
