[package]
name = "hasura-authn-jwt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
hasura-authn-core = { path = "../hasura-authn-core" }
lang-graphql = { path = "../../graphql/lang-graphql" }
open-dds = { path = "../../open-dds" }
tracing-util = { path = "../../utils/tracing-util"}

axum = { workspace = true }
cookie = { workspace = true }
jsonptr = { workspace = true }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true,  features = ["json"] }
schemars = { workspace = true, features = ["url"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
jsonwebkey = { workspace = true, features = ["generate", "jsonwebtoken","pkcs-convert"] }
mockito = { workspace = true }
openssl = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
