[package]
name = "hasura-authn-jwt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
hasura-authn-core = { path = "../hasura-authn-core" }
lang-graphql = { path = "../../lang-graphql" }
open-dds = { path = "../../open-dds" }
tracing-util = { path = "../../utils/tracing-util"}

axum = "0.6.20"
cookie = "0.18.1"
jsonptr = { version = "0.4.0" }
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
reqwest = { version = "0.11.8",  features = ["json"] }
schemars = { version = "0.8.12", features = ["url"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0"
url = "2.4.1"

[dev-dependencies]
anyhow = "1"
jsonwebkey = { version = "0.3.5", features = ["generate", "jsonwebtoken","pkcs-convert"] }
mockito = {version = "1.1.0", default-features = false, features = []}
openssl = "0.10.64"
tokio = { version = "1.29.0", features = ["macros"] }

[lints]
workspace = true
