type: bulk
args:

#Insert Author table data
- type: insert
  args:
    table: author
    objects:
      - id: 1
        name: Author 1
      - id: 2
        name: Author 2

#Insert aticle table data
- type: insert
  args:
    table: article
    objects:
    - id: 1
      version: 1.0.0
      content: Sample article 1, content version 1.0.0
      title: Article 1
      author_id: 1
      is_published: true
    - id: 2
      content: Sample article 1, content version 1.0.1
      version: 1.0.1
      title: Article 1
      author_id: 1
      is_published: false
    - id: 3
      content: Sample article 2, content version 1.0.2
      version: 1.0.0
      title: Article 2
      author_id: 2
      is_published: false

#Resident table
- type: run_sql
  args:
    sql: |
      INSERT INTO resident (name, age, city)
      VALUES  ('phillips', 25, 'canberra')
            , ('george', 26, 'sydney')
            , ('clarke', 21, 'perth')
      ;
