---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: graphiql
  name: graphiql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphiql
  template:
    metadata:
      labels:
        app: graphiql
    spec:
      containers:
      - image: hasura/base-git-image:0.7
        imagePullPolicy: IfNotPresent
        name: graphiql
        env:
        - name: GRAPHQL_ENDPOINT
          value: https://learn.hasura.io/graphql
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphiql
  name: graphiql
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: graphiql
  type: ClusterIP
