[package]
name = "hasura-authn-core"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open-dds = { path = "../open-dds" }
lang-graphql = { path = "../lang-graphql" }
thiserror = "1.0"
serde = "1.0.183"
serde_json = "1.0.105"
serde_with = "3.7.0"
lazy_static = "1.4.0"
tower = "0.4.13"
futures-util = "0.3.28"
axum = "0.6.20"
http = "0.2.9"
schemars = "0.8.12"

[dev-dependencies]
pretty_assertions = "1.3.0"
