[package]
name = "schema"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
hasura-authn-core = { path = "../auth/hasura-authn-core" }
json-ext = { path = "../utils/json-ext" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
metadata-resolve = {path = "../metadata-resolve" }

serde = "1.0.201"
serde_json = "1.0.116"
strum_macros = "0.26.2"
thiserror = "1.0"

[lints]
workspace = true
