[package]
name = "hasura-authn-webhook"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
hasura-authn-core = { path = "../hasura-authn-core" }
lang-graphql = { path = "../../lang-graphql" }
open-dds = { path = "../../open-dds" }
tracing-util = { path = "../../utils/tracing-util" }

axum = "0.6.9"
lazy_static = "1.4.0"
reqwest = { version = "0.11.8",  features = ["json"] }
schemars = { version = "0.8.12", features = ["smol_str", "url"] }
serde = "1.0.201"
serde_json = "1.0.116"
thiserror = "1.0"

[dev-dependencies]
mockito = { version = "1.1.0", default-features = false, features = [] }
rand = "0.8.5"
tokio = "1.29.0"

[lints]
workspace = true
