[package]
name = "hasura-authn-webhook"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
hasura-authn-core = { path = "../hasura-authn-core" }
lang-graphql = { path = "../../graphql/lang-graphql" }
open-dds = { path = "../../open-dds" }
tracing-util = { path = "../../utils/tracing-util" }

axum = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
schemars = { workspace = true, features = ["smol_str", "url"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
