[toolchain]
channel = "1.86.0"
profile = "default"  # see https://rust-lang.github.io/rustup/concepts/profiles.html
components = ["llvm-tools-preview", "rust-analyzer", "rust-src"]  # see https://rust-lang.github.io/rustup/concepts/components.html
