[package]
name = "dev-auth-webhook"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "dev-auth-webhook"
path = "src/main.rs"
bench = false

[dependencies]
tracing-util = { path = "../tracing-util" }

anyhow = "1"
axum = "0.6.20"
http = "0.2"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tower-http = { version = "0.4.4", features = ["trace"] }
