[package]
name = "hasura-authn"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hasura-authn-core = { path = "../hasura-authn-core" }
hasura-authn-jwt = { path = "../hasura-authn-jwt" }
hasura-authn-noauth = { path = "../hasura-authn-noauth" }
hasura-authn-webhook = { path = "../hasura-authn-webhook" }
jsonpath = { path = "../../utils/jsonpath" }
open-dds = { path = "../../open-dds" }
opendds-derive = { path = "../../utils/opendds-derive" }
tracing-util = { path = "../../utils/tracing-util" }

anyhow = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true}
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
pretty_assertions = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
  "jsonpath",            # used by opendds-derive
  "serde_path_to_error", # used by opendds-derive
]

[lints]
workspace = true
