description: User can query geometry values which satisfies filter in select permission
url: /v1/graphql
status: 200
headers:
  X-Hasura-Role: user1
response:
  data:
    geom_table:
    - id: 3
      type: linestring
      geom_col:
        type: LineString
        coordinates:
        - - 1
          - 0
        - - 0.5
          - 0.5
        - - 0
          - 1
    - id: 4
      type: polygon
      geom_col:
        type: Polygon
        coordinates:
        - - - 0
            - 0
          - - 0
            - 1
          - - 1
            - 1
          - - 1
            - 0
          - - 0
            - 0
    - id: 5
      type: polygon
      geom_col:
        type: Polygon
        coordinates:
        - - - 2
            - 0
          - - 2
            - 1
          - - 3
            - 1
          - - 3
            - 0
          - - 2
            - 0

query:
  query: |
    query {
      geom_table{
        id
        type
        geom_col
      }
    }
