[package]
name = "open-dds"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
opendds-derive = { path = "../opendds-derive" }

derive_more = "0.99.17"
indexmap = { version = "2", features = ["serde"] }
lazy_static = "1.4.0"
ndc-models = { git = "https://github.com/hasura/ndc-spec.git", tag = "v0.1.2" }
schemars = { version = "0.8.12", features = ["smol_str", "preserve_order"] }
serde = "1.0.152"
serde_json = { version = "1.0.92", features = ["preserve_order"] }
serde_path_to_error = "0.1.14"
strum = "0.26.2"
strum_macros = "0.25.2"
thiserror = "1.0"

[dev-dependencies]
goldenfile = "^1.4.5"
pretty_assertions = "1.3.0"

[package.metadata.cargo-machete]
ignored = [
  "strum", # used by strum_macros
]

[lints]
workspace = true
