[package]
name = "open-dds"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
jsonpath = { path = "../utils/jsonpath" }
jsonschema-tidying = { path = "../utils/jsonschema-tidying" }
opendds-derive = { path = "../utils/opendds-derive" }

derive_more = { workspace = true }
indexmap = { workspace = true }
ndc-models = { workspace = true }
ndc-models-v01 = { workspace = true }
ref-cast = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
smol_str = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true
