[package]
name = "graphql-ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
graphql-schema = { path = "../../graphql/schema" }
hasura-authn-core = { path = "../../auth/hasura-authn-core" }
json-ext = { path = "../../utils/json-ext" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../../open-dds" }
plan = { path = "../../plan" }
plan-types = { path = "../../plan-types" }
tracing-util = { path = "../../utils/tracing-util" }
metadata-resolve = {path = "../../metadata-resolve" }

base64 = { workspace = true }
indexmap = { workspace = true }
nonempty = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
transitive = { workspace = true }

[lints]
workspace = true
