- description: Try to add a GET rest endpoint with no argument with path segments
    in it
  url: /v1/query
  status: 200
  response:
    message: success
  query:
    type: create_rest_endpoint
    args:
      url: simple/with/segments
      name: simple_with_segments
      methods:
      - GET
      definition:
        query:
          collection_name: test_collection
          query_name: simple_query

- description: Try to add a POST rest endpoint with arguments in URL and with path
    segments in it
  url: /v1/query
  status: 200
  response:
    message: success
  query:
    type: create_rest_endpoint
    args:
      url: simple/with/segments/:first_name/:last_name/trailing
      name: with_args_and_segments_url
      methods:
      - POST
      definition:
        query:
          collection_name: test_collection
          query_name: query_with_args

- description: Call openapi json endpoint
  url: /api/swagger/json
  method: GET
  status: 200
  query:
  response:
    openapi: 3.0.0
    info:
      description: This OpenAPI specification is automatically generated by Hasura.
      title: Rest Endpoints
      version: ''
    paths:
      /api/rest/simple/with/segments:
        get:
          summary: simple_with_segments
          description: "***\nThe GraphQl query for this endpoint is:\n``` graphql\n\
            query { test_table { first_name last_name } }\n```"
          parameters:
          - description: Your x-hasura-admin-secret will be used for authentication
              of the API request.
            in: header
            name: x-hasura-admin-secret
            schema:
              type: string
          responses:
            '200':
              content:
                application/json:
                  schema:
                    properties:
                      test_table:
                        items:
                          description: columns and relationships of "test_table"
                          nullable: false
                          properties:
                            first_name:
                              nullable: true
                              title: String
                              type: string
                            last_name:
                              nullable: true
                              title: String
                              type: string
                          title: test_table
                          type: object
                        nullable: false
                        type: array
              description: Responses for GET /api/rest/simple/with/segments
      /api/rest/simple/with/segments/{first_name}/{last_name}/trailing:
        post:
          summary: with_args_and_segments_url
          description: "***\nThe GraphQl query for this endpoint is:\n``` graphql\n\
            query ($first_name: String!, $last_name:String!) { test_table(where: {first_name:\
            \ { _eq: $first_name } last_name: { _eq: $last_name }}) { first_name last_name\
            \ } }\n```"
          parameters:
          - description: Your x-hasura-admin-secret will be used for authentication
              of the API request.
            in: header
            name: x-hasura-admin-secret
            schema:
              type: string
          - description: _"first_name" is required (enter it either in parameters
              or request body)_
            in: path
            name: first_name
            schema:
              type: string
          - description: _"last_name" is required (enter it either in parameters or
              request body)_
            in: path
            name: last_name
            schema:
              type: string
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    first_name:
                      nullable: false
                      title: String
                      type: string
                    last_name:
                      nullable: false
                      title: String
                      type: string
                  type: object
            description: Query parameters can also be provided in the request body
              as a JSON object
            required: false
          responses:
            '200':
              content:
                application/json:
                  schema:
                    properties:
                      test_table:
                        items:
                          description: columns and relationships of "test_table"
                          nullable: false
                          properties:
                            first_name:
                              nullable: true
                              title: String
                              type: string
                            last_name:
                              nullable: true
                              title: String
                              type: string
                          title: test_table
                          type: object
                        nullable: false
                        type: array
              description: Responses for POST /api/rest/simple/with/segments/{first_name}/{last_name}/trailing
    components: {}

- description: Try to remove the endpoint
  url: /v1/query
  status: 200
  response:
    message: success
  query:
    type: drop_rest_endpoint
    args:
      name: simple_with_segments

- description: Try to remove the endpoint
  url: /v1/query
  status: 200
  response:
    message: success
  query:
    type: drop_rest_endpoint
    args:
      name: with_args_and_segments_url
