[package]
name = "graphql-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bench]]
name = "generate_ir"
harness = false

[dependencies]
execute = { path = "../../execute" }
graphql-schema = { path = "../schema" }
hasura-authn-core = { path = "../../auth/hasura-authn-core" }
graphql-ir = { path = "../ir" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../../open-dds" }
plan-types = { path = "../../plan-types" }
tracing-util = { path = "../../utils/tracing-util" }
metadata-resolve = {path = "../../metadata-resolve" }

async-recursion = { workspace = true }
axum = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
ndc-models = { workspace = true }
ndc-models-v01 = { workspace = true }
nonempty = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports", "async_tokio"] }
goldenfile = { workspace = true }

[lints]
workspace = true
