[package]
name = "metadata-resolve"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
hasura-authn-core = { path = "../auth/hasura-authn-core" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }

derive_more = "0.99.17"
indexmap = { version = "2", features = ["serde"] }
lazy_static = "1.4.0"
ndc-models = { git = "https://github.com/hasura/ndc-spec.git", tag = "v0.1.2" }
nonempty = "0.10"
ref-cast = "1.0"
reqwest = { version = "0.11", features = ["json", "multipart"] }
serde = "1.0.201"
serde_json = "1.0.116"
thiserror = "1.0"
url = "2.4.1"

[lints]
workspace = true
