[package]
name = "dev-auth-webhook"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "dev-auth-webhook"
path = "src/main.rs"
bench = false

[dependencies]
tracing-util = { path = "../../utils/tracing-util" }

anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
