[package]
name = "execute"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[[bench]]
name = "generate_ir"
harness = false

[dependencies]
hasura-authn-core = { path = "../auth/hasura-authn-core" }
json-ext = { path = "../utils/json-ext" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
schema = { path = "../schema" }
tracing-util = { path = "../utils/tracing-util" }
metadata-resolve = {path = "../metadata-resolve" }

async-recursion = "1.1.1"
axum = { version = "0.6.20" }
base64 = "0.22.1"
bytes = "1.6.0"
derive_more = "0.99.17"
futures-util = "0.3"
indexmap = { version = "2", features = ["serde"] }
ndc-models = { git = "https://github.com/hasura/ndc-spec.git", tag = "v0.1.2" }
nonempty = "0.10"
reqwest = { version = "0.11", features = ["json", "multipart"] }
schemars = { version = "0.8.12", features = ["smol_str"] }
serde = "1.0.201"
serde_json = "1.0.116"
thiserror = "1.0"
tokio = { version = "1.26.0", features = [
  "macros",
  "parking_lot",
  "rt-multi-thread",
  "signal",
] }
transitive = "0.5.0"
url = "2.4.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
goldenfile = "1.7.1"
mockito = { version = "1.1.0", default-features = false, features = [] }
pretty_assertions = "1.3.0"

[lints]
workspace = true
