[package]
name = "execute"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
engine-types = { path = "../engine-types" }
graphql-schema = { path = "../graphql/schema" }
hasura-authn-core = { path = "../auth/hasura-authn-core" }
graphql-ir = { path = "../graphql/ir" }
json-ext = { path = "../utils/json-ext" }
lang-graphql = { path = "../graphql/lang-graphql" }
open-dds = { path = "../open-dds" }
plan-types = { path = "../plan-types" }
tracing-util = { path = "../utils/tracing-util" }
metadata-resolve = {path = "../metadata-resolve" }
futures-ext = { path = "../utils/futures-ext" }
query-usage-analytics = { path = "../query-usage-analytics" }

async-recursion = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
ndc-models = { workspace = true }
ndc-models-v01 = { workspace = true }
nonempty = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
transitive = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true
