[package]
name = "jsonapi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
execute = { path = "../execute" }
hasura-authn-core = { path = "../auth/hasura-authn-core" }
jsonpath = { path = "../utils/jsonpath" }
metadata-resolve = { path = "../metadata-resolve" }
open-dds = { path = "../open-dds" }
plan = { path = "../plan" }
tracing-util = { path = "../utils/tracing-util" }

axum = { workspace = true }
axum-core = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
jsonapi_library = { workspace = true }
ndc-models = { workspace = true }
oas3 = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["glob","json"] }
reqwest = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["error_chain", "log", "queryst", "serde", "serde_derive" ]
