[package]
name = "json-annotation-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonpath = { path = "../jsonpath" }
indexmap = "2.11.4"
nom = "7.1.3"
nom_locate = "4.2.0"
