# These services are brought up in 'run.sh' (see that file)

version: "3.6"

name: hge-python-tests

services:
  postgres:
    extends:
      file: ../../docker-compose/databases.yaml
      service: postgres
    environment:
      POSTGRES_PASSWORD: "hasura"
    volumes:
      - ./docker/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    deploy:
      replicas: 2

  citus:
    extends:
      file: ../../docker-compose/databases.yaml
      service: citus
    environment:
      POSTGRES_PASSWORD: "hasura"

  sqlserver:
    extends:
      file: ../../docker-compose/databases.yaml
      service: sqlserver
